### ISSUE TITLE
v.1.13d, wrapper v.0.91.325 : Crash when quitting solo game during Shenk's death shenanigans

### ISSUE THREAD

**Issue by eleriaqueen** [bolrog/d2gx#11]
How to reproduce : Start a 1.13d (wrapper v.0.91.325) solo game on normal, warp to shenk, kill it and wait for more effects to appear then Save&Exit, game should crash.

**Comment by eleriaqueen** [comment]
Nice, grab this if you need testing characters.
[Diablo II Testing Characters.zip](https://github.com/bolrog/d2gx/files/6211114/Diablo.II.Testing.Characters.zip)

**Comment by bolrog** [comment]
Thanks. I found some ridiculous savegame where I'm whizzing around killing everything without looking. Perfect for stress testing. :)

I've uploaded version 0.91.327, which hopefully solves the issue for you.

**Comment by eleriaqueen** [comment]
Did a few Shenk kills followed by a timed Save&Quit, game didn't crash. The issue -seems- solved.

**Comment by bolrog** [comment]
Great, I'll close this for now.
